import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      // Material-3 palette, ported verbatim from the Stitch design.
      colors: {
        background: "#f9f9ff",
        surface: "#f9f9ff",
        "surface-bright": "#f9f9ff",
        "surface-dim": "#d9d9e0",
        "surface-variant": "#e2e2e8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f9",
        "surface-container": "#eeedf4",
        "surface-container-high": "#e8e7ee",
        "surface-container-highest": "#e2e2e8",
        "surface-tint": "#335ea1",
        "on-background": "#1a1c20",
        "on-surface": "#1a1c20",
        "on-surface-variant": "#434750",
        "inverse-surface": "#2f3035",
        "inverse-on-surface": "#f0f0f6",
        primary: "#063f81",
        "primary-container": "#2b579a",
        "on-primary": "#ffffff",
        "on-primary-container": "#b7cfff",
        "primary-fixed": "#d7e3ff",
        "primary-fixed-dim": "#abc7ff",
        "on-primary-fixed": "#001b3f",
        "on-primary-fixed-variant": "#134688",
        "inverse-primary": "#abc7ff",
        secondary: "#615f52",
        "secondary-container": "#e4e0d0",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#656356",
        "secondary-fixed": "#e7e3d3",
        "secondary-fixed-dim": "#cac7b7",
        "on-secondary-fixed": "#1d1c12",
        "on-secondary-fixed-variant": "#49473b",
        tertiary: "#633500",
        "tertiary-container": "#844900",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffc28d",
        "tertiary-fixed": "#ffdcc1",
        "tertiary-fixed-dim": "#ffb877",
        "on-tertiary-fixed": "#2e1600",
        "on-tertiary-fixed-variant": "#6c3a00",
        outline: "#737782",
        "outline-variant": "#c3c6d2",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-gap": "4px",
        "edge-margin": "16px",
        "binder-gutter": "40px",
        "cell-padding": "8px",
      },
      fontFamily: {
        "mono-data": ["JetBrains Mono", "ui-monospace", "monospace"],
        "headline-lg": ["Source Serif 4", "Georgia", "serif"],
        "headline-md": ["Source Serif 4", "Georgia", "serif"],
        "label-sm": ["IBM Plex Sans", "system-ui", "sans-serif"],
        "body-lg": ["IBM Plex Sans", "system-ui", "sans-serif"],
        "body-md": ["IBM Plex Sans", "system-ui", "sans-serif"],
        sans: ["IBM Plex Sans", "system-ui", "sans-serif"],
        serif: ["Source Serif 4", "Georgia", "serif"],
      },
      fontSize: {
        "mono-data": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [forms({ strategy: "class" }), containerQueries],
};
